### ISSUE TITLE
blink_piface crashes on startup

### ISSUE THREAD

**Issue by pedromorgan** [luismesas/goPi#5]
> go run blink_piface.go

SIGILL: illegal instruction
PC=0x3559c

math.init·1()
    /usr/lib/go/src/pkg/math/pow10.go:34 +0x28
math.init()
    /usr/lib/go/src/pkg/math/unsafe.go:21 +0x70
fmt.init()
    /usr/lib/go/src/pkg/fmt/scan.go:1164 +0x70
github.com/luismesas/goPi/spi.init()
    /home/pi/gogo/src/github.com/luismesas/goPi/spi/spi.go:71 +0x78
main.init()
    /home/pi/gogo/src/github.com/pedromorgan/goPi/examples/blink_piface/blink_piface.go:29 +0x74

goroutine 2 [runnable]:
created by runtime.main
    /golang-1.0.2/src/pkg/runtime/proc.c:221

trap    0x6
error   0x0
oldmask 0x0
r0      0x502970
r1      0x0
r2      0x0
r3      0x2
r4      0x0
r5      0x0
r6      0x0
r7      0x0
r8      0x0
r9      0xf4c84
r10     0x1061e000
fp      0x502627
ip      0xcafebabe
sp      0xb6f66f54
lr      0x35b30
pc      0x3559c
cpsr    0x20000010
fault   0x0
exit status 2

**Comment by pedromorgan** [comment]
CLose this... With golang1.3 no problems (previous was go 1.0.2 !)

**Comment by pedromorgan** [comment]
aha can close myself..
